app/urls.py
from django.urls import path
from . import views
urlpatterns = [
	path('home1',views.home1,name='home1'),
    path('reg',views.reg,name='reg'),
    path('logout',views.logout,name='logout'),
	path('booksum',views.booksum),
	path('bss',views.bss),
	path('newbooking',views.newbooking,name='newbooking'),
	path('generate',views.generate),
	path('newbooking',views.newbooking),
	path('receipt',views.receipt,name='receipt'),
	path('confirmletter',views.confirmletter),
	path('project',views.project,name='project'),
	path('update_data/<int:id>',views.update_data, name='update_data'),
	path('delete_data/<str:id>',views.delete_data, name='delete_data'),
    path('ugdg',views.ugdg,name='ugdg'),
    path('transfer',views.transfer,name='transfer'),
    path('cancel',views.cancel,name='cancel'),
    path('leadowner',views.leadowner,name='leadowner'),
    path('site_visit',views.site_visit,name='site_visit')
]

bsnl/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('page.urls')),
    path('login/',include('dashboard.userinfo.urls')),
    path('members/',include('dashboard.members.urls')),
    path('projects/',include('dashboard.projects.urls')),
    path('reports/',include('dashboard.reports.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/reports/urls.py
from django.urls import path
from dashboard.reports import views


urlpatterns=[
    path('confirmletter_view/<id>',views.confirmletter_view,name='confirmletter_view'),
    path('print_recepit/<id>',views.print_recepit,name='print_recepit'),
    path('bookingreport',views.booking_report,name='booking_report'),
    path('sitereport',views.site_report,name='site_report'),
    path('pdcreport',views.pdc_report,name='pdc_report'),
    path('ugdgreport',views.ugdg_report,name='ugdg_report'),
    path('transferreport',views.transfer_report,name='transfer_report'),
    path('cancelreport',views.cancel_report,name='cancel_report'),
    path('receiptdetails',views.receipt_details,name='receipt_details'),
]

dashboard/reports/models.py
from django.db import models

# Create your models here.

dashboard/userinfo/models.py
from django.db import models
from bsnl import settings
from django.contrib.auth.hashers import make_password

from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
       
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),

        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
       
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user
    



class User(AbstractBaseUser):
    role = models.CharField(max_length=10, null=True)
    User = models.EmailField(verbose_name='email', max_length=100, unique=True, null=True) 
    email = models.EmailField(verbose_name='email', max_length=100, unique=True, null=True) 
    first_name = models.CharField(max_length=50, null=True) 
    last_name = models.CharField(max_length=50, null=True) 
    mobile_no = models.CharField(max_length=50, null=True)
    is_details_added = models.BooleanField(default=False, null=True)
    is_password_set = models.BooleanField(default=False, null=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    date_create = models.DateTimeField(auto_now_add=True, null=True)
    date_joined=models.CharField(max_length=50,null=True)
    objects = MyUserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['password']
    login_type = models.CharField(max_length=50,null=True)
    employee_id = models.CharField(max_length=50,null=True)

    def save(self, *args, **kwargs):
        self.s_password = make_password(self.password)
        super(User, self).save(*args, **kwargs)
   

class UserDetail(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING, null=False)
    dob = models.DateField(null=True)
    age = models.CharField(max_length=3,null=True)
    email = models.EmailField(max_length=100,null=True)
    alternate_no = models.CharField(max_length=20,null=True)
    address = models.CharField(max_length=300,null=True)
    city =  models.CharField(max_length=300,null=True)
    state =  models.CharField(max_length=300,null=True)
    pincode = models.CharField(max_length=20,null=True)
    panno = models.CharField(max_length=20,null=True)
    aadhhaarno = models.CharField(max_length=20,null=True)
    profile = models.ImageField(upload_to= settings.PROFILE_UPLOAD_PATH, null=True)    
    aadhar_proof = models.ImageField(upload_to= settings.AADHAR_UPLOAD_PATH, null=True)  
    pan_proof = models.ImageField(upload_to= settings.PAN_UPLOAD_PATH, null=True)  
    created_by = models.IntegerField(null=True)
    modified_by = models.IntegerField(null=True)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)
    id_card=models.CharField(max_length=30,default='Pending')
    
class UserNominee(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING, null=False)
    nominee_name=models.CharField(max_length=100,null=True)
    nominee_age=models.CharField(max_length=10,null=True)
    address = models.CharField(max_length=300,null=True)
    city =  models.CharField(max_length=300,null=True)
    state =  models.CharField(max_length=300,null=True)
    nominee_relationship=models.CharField(max_length=20,null=True)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)


class UserFamilyDetails(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=False)
    member_name=models.CharField(max_length=100,null=True)
    member_age=models.CharField(max_length=10,null=True)
    member_relation = models.CharField(max_length=300,null=True)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)

class SeniorTeamLead(models.Model):
    user = models.ForeignKey(User,  on_delete=models.DO_NOTHING, null=False)
    project_head = models.ForeignKey(User, related_name="project_head", on_delete=models.DO_NOTHING, null=False)

class TeamLead(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=False)
    sr_team = models.ForeignKey(SeniorTeamLead, on_delete=models.DO_NOTHING, null=False)

class Executive(models.Model):
    user = models.ForeignKey(User,  on_delete=models.DO_NOTHING, null=False)
    teamlead = models.ForeignKey(TeamLead, on_delete=models.DO_NOTHING, null=False)

dashboard/reports/views.py
from django.shortcuts import render,redirect,HttpResponse
from dashboard.members.models import Bookings,PaymentDetails,Site_visit
from dashboard.projects.models import Project
from dashboard.userinfo.models import UserDetail,Executive,User,SeniorTeamLead
from django.urls import reverse
from num2words import num2words
from django.db.models import Sum
from datetime import datetime, date, timedelta
from django import template
from django.core.exceptions import ObjectDoesNotExist
from datetime import datetime
from collections import defaultdict
# Create your views here.

def confirmletter_view(request,id):
    book=Bookings.objects.get(id=id)
    user = User.objects.get(id=book.user_id)
    userdetail = UserDetail.objects.get(user=book.user)
    payment = PaymentDetails.objects.filter(booking=book)
    project = Project.objects.filter(landdetails=book.land_details)
    first_payment = PaymentDetails.objects.filter(booking=book)[1]
    if first_payment:
        bank = first_payment.bank
        branch = first_payment.branch
        amount = first_payment.amount
        cheque_no = first_payment.cheque_no
        dd_no = first_payment.ddno
        netbanking = first_payment.transaction
        print("Bank:", bank)
        print("Branch:", branch)
        print("Amount:", amount)
    else:
        print("No payments found for this booking.")




   
    # for i in payment:
    #     bank = i.bank
    #     return render(request ,'confirmletter_view.html',{'book1':bank})
    # print("Muthu")
    return render(request,'confirmletter_view.html',{'user':user,
                                                     'book':book,
                                                     'amount':amount if 'amount' in locals() else None,
                                                     'bank':bank  if 'bank' in locals() else None,
                                                     'branch':branch  if 'branch' in locals() else None,
                                                     'userdetail':userdetail,
                                                     'payment':payment,
                                                     'netbanking':netbanking,
                                                     'dd_no':dd_no,
                                                     'cheque_no':cheque_no,
                                                     'project':project})
 

def print_recepit(request, id):
    try:
        paymentInfos = PaymentDetails.objects.filter(receipt_no=id).first()
        data = PaymentDetails.objects.filter()
      
        check_payments = PaymentDetails.objects.filter(dateofreceipt=paymentInfos.dateofreceipt , booking_id=paymentInfos.booking_id)
        details = PaymentDetails.objects.filter(receipt_no = paymentInfos.receipt_no, booking_id=paymentInfos.booking_id)
       
        for i in check_payments:
            
            if i.paymentname == "DownPayment":
                Value = PaymentDetails.objects.filter(dateofreceipt=paymentInfos.dateofreceipt , booking_id=paymentInfos.booking_id)
            else:
                Value = PaymentDetails.objects.filter(receipt_no = paymentInfos.receipt_no, booking_id=paymentInfos.booking_id)
      
       
        user = Bookings.objects.filter(user_id=paymentInfos.booking.user_id).first()
        senpayment = Bookings.objects.get(id = paymentInfos.booking_id)
        if not user:
            return HttpResponse("No booking found for receipt number: {}".format(id))
       

        userdetail = UserDetail.objects.get(user=user.user)
        payments = PaymentDetails.objects.filter(booking_id=user.id)
        payment_count = payments.values('receipt_no').distinct().count()
        
        id=id
        total = 0
        for payment in payments:
            name = payment.paymentname
            last_payment = float(payment.amount)
            total = int(last_payment)
           
            
        if last_payment:
            no = int(last_payment)
            receipt_no = num2words(no)
        get_last = PaymentDetails.objects.filter(booking_id=user.id).last()
        value = get_last.amount
        no = int(float(value)) 
        amont = int(float(value)+2600)  
        word1 = num2words(amont, lang='en_IN')
        word = word1.replace(',','')
        id=id 
       
        data = PaymentDetails.objects.all()
        total_amount_per_receipt = defaultdict(int)
        for detail in data:
            total_amount_per_receipt[detail.receipt_no] += int(float(detail.amount))

        downpayments = {}
        for receipt_no, total_amount in total_amount_per_receipt.items():
            total_amount_words = num2words(total_amount, lang='en_IN')
            total_amount_words = total_amount_words.replace(',','')
            downpayments[receipt_no] = total_amount_words
        context = {
            'id': id,
            'downpayments':downpayments,
            'user': user,   
            'detail':details,
            'senpayment':senpayment,
            'word':word,
            'Value':Value,
            'userdetail': userdetail,
            'payment': payments,
            'payment_count': payment_count,
            'total_amount_per_receipt': total_amount_per_receipt.items(),
            'total_all': check_payments.aggregate(Sum('amount'))['amount__sum'],
            'check_payment': check_payments
        }
        return render(request, 'print_recepit.html', context)
    except Exception as e:
        return HttpResponse("An error occurred: {}".format(e))
    
register = template.Library()

@register.filter
def add_amount(value):
    return int(value) + 2600

def booking_report(request):

    view_report = PaymentDetails.objects.all()
    project = Project.objects.all()
    bookings =Bookings.objects.all().order_by('-created_on')
    team_lead = User.objects.filter( role = "Project_Lead")
    executivename = User.objects.filter( role = "Executive")     
    
    if request.method == 'POST':
        data = request.POST.get('paymenttype')
        value = request.POST.get('projectOption')
        select = request.POST.get('reportType')
        teamlead = request.POST.get('projectOption')
        executtype = request.POST.get('projectexecut')
        if select == 'project':
            if value == 'all':
                bookings = Bookings.objects.all().order_by('-created_on')
                print("All", bookings)
            else:
                bookings = Bookings.objects.filter(land_details__project__projectname = value).order_by('-created_on')
            for booking in bookings:
                payments = booking.paymentdetails_set.all()
                booking.total_amt = payments.aggregate(Sum('amount'))['amount__sum']
                booking.address = UserDetail.objects.get(user_id = booking.user.id).address
                booking.alter = UserDetail.objects.get(user_id = booking.user.id).alternate_no
        elif select == 'date':
            fromDate = request.POST.get('fromDate','')
            toDate = request.POST.get('toDate','')
            if toDate and fromDate:
                date_obj = datetime.strptime(toDate, '%Y-%m-%d')
                fromDate = datetime.strptime(fromDate, '%Y-%m-%d')
                date_obj = datetime.strptime(toDate, '%Y-%m-%d')
                toDate =  date_obj + timedelta(days=1)
                bookings = Bookings.objects.filter(created_on__gte=date(fromDate.year, fromDate.month, fromDate.day),
                                                   created_on__lte=date(date_obj.year, date_obj.month, date_obj.day)).all().order_by('-created_on')
                for booking in bookings:
                    payments = booking.paymentdetails_set.all()
                    booking.total_amt = payments.aggregate(Sum('amount'))['amount__sum']
                    booking.address = UserDetail.objects.get(user_id = booking.user.id).address
                    booking.alter = UserDetail.objects.get(user_id = booking.user.id).alternate_no     
                    
  
        elif select == 'project_head':
            
            #bookings = Bookings.objects.filter(sitevist__executive__executive_set__last__teamlead__sr_team__project_head__first_name= teamlead)
            sites = Site_visit.objects.filter(proj_head_id=teamlead)
            bookings = Bookings.objects.filter(sitevist__id=1).order_by('-created_on')

        elif select == 'executive':
            bookings = Bookings.objects.filter(sitevist__executive = executtype).order_by('-created_on')
        elif select == 'payment_type':
            if data == 'DownPayment':
                print('DownPayment',data)
                bookings = Bookings.objects.filter(payments_status__in=[1,4])
            elif data == 'FirstInstallment':
                bookings = Bookings.objects.filter(payments_status__in=[3,6])
                print('1st',data)
            elif data == 'SecondInstallment':
                print('2nd',data)
                bookings = Bookings.objects.filter(payments_status__in=[5,8])
            elif data == 'ThridInstallment':
                print('3rd',data)
                bookings = Bookings.objects.filter(payments_status__in=[7,9])
        else:
            booking = Bookings.objects.all().order_by('-created_on')
            executive_id = SeniorTeamLead.objects.all()
            print(booking)
            for i in executive_id:
                print("id",i.user)
            for booking in bookings:
                payments = booking.paymentdetails_set.all()
                booking.total_amt = payments.aggregate(Sum('amount'))['amount__sum']
                booking.address = UserDetail.objects.get(user_id = booking.user.id).address
                booking.alter = UserDetail.objects.get(user_id = booking.user.id).alternate_no

        context={
        'view_report': view_report,
        'project':project,
        'bookings':bookings,
        'team_lead':team_lead,
        'executivename':executivename,
        }

dashboard/reports/templates/cancel_report.html
{% extends 'index.html' %}
{% block content %}
{% load static %}
{% include 'common/bootstrap.html' %}
<style>
    a {
        color: black;
    }
</style>
<br>
<div class=" p-1" style=" box-shadow:0px 0px 5px #007bff; border-radius: 10px;">
    <form class="pt-5" method="post">
        <label class="text-lg dark:text-white-light p-2 font-weight-bold addproject"
            style="background-color: #178EF0;color:white; width:100%;">
            <center><b>CANCELLATION DETAILS</b></center>
        </label>
        {% csrf_token %}
        {% for message in messages %}
  <div
    class="alert {% if message.tags == 'error' %} alert-danger {% elif message.tags == 'success' %} alert-success {% endif %}"
  >
    <a class="close" href="#" data-dismiss="alert">×</a>
    {{ message }}
  </div>
  {% endfor %}
        <div class="grid grid-cols-1 md:grid-cols-3 gap-5">
            <div class="p-1">
                <label class="p-1">Select Report Type</label>
                <select class="form-control" id="reportType" name="reportType">
                    <option disabled selected hidden>Select Report</option>
                    <option value="date">Cancel Date Wise</option>
                    <option value="refunddate">Refund Date Wise</option>
                    <option value="project_head">Proj Head Wise</option>
                    <option value="mode_wise">Mode of Refund Wise</option>
                    <option value="type_wise">Type of Refund Wise</option>
                </select>
            </div>
            <div id="dynamicDropdown" style="display: none;" class="p-1">
            </div>
        </div>
        <div>
            <a  id="cancelreportlink" style="float: right;" class="btn btn-primary">Download CSV</a>
            <button class="btn btn-primary mr-1" style="float: right;" type="submit" name="reportType" value="all">All</button>
        </div>
    </form>
    <br>
    <div>
        <table class="table-responsive" class="emInfo responsive">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Date_of_Cancel</th>
                    <th>Date_of_Refund</th>
                    <th>Mode_of_Refund</th>
                    <th>Type_of_Refund</th>
                    <th>Refund_Cheque No</th>
                    <th>Refund_Amount</th>
                    <th>Issued_by</th>
                    <th>Executive Name</th>
                    <th>Proj Head Name</th>
                    <th>Dimension</th>
                </tr>
            </thead>
            <tbody>
                {% for val in cancelreport_filter %}
                {% if val.date_of_cancel %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{val.date_of_cancel}}</td>
                    <td>{{val.date_of_refund}}</td>
                    <td>{{val.mode_of_refund}}</td>
                    <td>{{val.type_of_refund}}</td>
                    <td>{{val.refund_cheque_no}}</td>
                    <td>{{val.refund_amount}}</td>
                    <td>{{val.issued_by}}</td>
                    <td>{{val.executive.first_name}}</td>
                    <td>{{val.projhead.first_name}}</td>
                    <td>{{val.land_details.plotsize.plotsize}}</td>
                </tr>
                {% endif %}

                {%endfor%}
            </tbody>
        </table>
    </div>

    <div class="modal fade bd-example-modal-sm" id="exampleModal" tabindex="-1" role="dialog"
        aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Select Date</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="post" action="{% url 'cancel_report' %}">
                    {% csrf_token %}
                    <input type="hidden" name="date" value=date>
                    <div class="modal-body">
                        <div class="form-group">
                            <label>From Date</label>
                            <input type="hidden" name="reportType" value=date>
                            <input type="date" class="form-control" name="fromDate" value="" required="">
                        </div>
                        <div class="form-group">
                            <label>To Date</label>

                            <input type="date" class="form-control" name="toDate" value="" required="">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="reset" class="btn btn-secondary">Reset</button>
                        <button type="submit" class="btn btn-primary">Apply</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade bd-example-modal-sm" id="refunddatewise" tabindex="-1" role="dialog"
        aria-labelledby="refunddatewiseLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="refunddatewiseLabel">Select Date</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="post" action="{% url 'cancel_report' %}">
                    {% csrf_token %}
                    <input type="hidden" name="refunddate" value=refunddate>
                    <div class="modal-body">
                        <div class="form-group">
                            <label>From Date</label>
                            <input type="hidden" name="reportType" value=refunddate>
                            <input type="date" class="form-control" name="fromDate" value="" required="">
                        </div>
                        <div class="form-group">
                            <label>To Date</label>

                            <input type="date" class="form-control" name="toDate" value="" required="">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="reset" class="btn btn-secondary">Reset</button>
                        <button type="submit" class="btn btn-primary">Apply</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    var reportTypeDropdown = document.getElementById('reportType');
    var dynamicDropdown = document.getElementById('dynamicDropdown');

    reportTypeDropdown.addEventListener('change', function () {
        var selectedOption = reportTypeDropdown.value;
        
        if (selectedOption === 'all') {
            location.reload();

        } else if (selectedOption === 'date') {
            dynamicDropdown.innerHTML = `
                <label class="p-1">Select canceled date</label>
                <input type="hidden" name="reportType" value='date'> 
                    <div class="card-tools">
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                              <i class="fas fa-filter"></i>Filter
                            </button>
                        </div>
                
            `;
            dynamicDropdown.style.display = 'block';
            // 2nd block
        } else if (selectedOption === 'refunddate') {
            dynamicDropdown.innerHTML = `
                <label class="p-1">Select Refund Date</label>
                <input type="hidden" name="reportType" value=date> 
                    <div class="card-tools">
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#refunddatewise">
                              <i class="fas fa-filter"></i>Filter
                            </button>
                        </div>
                
            `;
            dynamicDropdown.style.display = 'block';
            // 3rd block
        } else if (selectedOption === 'project_head') {
            dynamicDropdown.innerHTML = `
            {% csrf_token %}
            <label class="p-1">Proj Head Wise</label>
            <input type="hidden" name="reportType" value ='project_head'> 
                <select class="form-control" id="projecthead" name="cancelreportoption" onchange="this.form.submit()">
                    <option disabled selected hidden>Select Report Type</option>
                    {% for mydata in team_lead %}
                        <option value="{{ mydata.id }}">{{ mydata.first_name }}</option>
                    {% endfor %}
                </select>
            `;
            dynamicDropdown.style.display = 'block';
            // 4th block 
        } else if (selectedOption === 'mode_wise') {
            dynamicDropdown.innerHTML = `
            <label class="p-1">Mode Of Refund Wise</label>
            <input type="hidden" name="reportType" value = 'mode_wise'>
                <select class="form-control" id="projectexe" name="cancelreportoption" onchange="this.form.submit()">
                    <option disabled selected hidden>Select</option>
                    <option value="Cheque">Cheque</option>
                    <option value="DD">DD</option>
                </select>
            `;
            dynamicDropdown.style.display = 'block';
            // 5th block
        } else if (selectedOption === 'type_wise') {
            dynamicDropdown.innerHTML = `
            <label class="p-1">Type Of Refund Wise</label>
            <input type="hidden" name="reportType" value = 'type_wise'>
                <select class="form-control" id="projectexe" name="cancelreportoption" onchange="this.form.submit()">
                    <option disabled selected hidden>Select</option>
                    <option value="Part Refund">Part Refund</option>
                    <option value="Full Refund">Full Refund</option>
                    <option value="Zero Payments">Zero Payments</option>
                </select>
            `;
            dynamicDropdown.style.display = 'block';
            // 6th block
        } else {
            dynamicDropdown.style.display = 'none';
        }
    });
</script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var cancelreportlink = document.getElementById('cancelreportlink');
        cancelreportlink.addEventListener('click', function () {
            // Prepare data for CSV
            var csvContent = "data:text/csv;charset=utf-8,";
            csvContent += "Date_of_Cancel,Date_of_Refund,Mode_of_Refund,Type_of_Refund,Refund_Cheque No,Refund_Amount,Issued_by,Executive Name,Proj Head Name,Dimension\n";
            // Loop through the bookings data and append to CSV
            {% for val in cancelreport_filter %}
            {% if val.date_of_cancel %}
                csvContent += "{{ val.date_of_cancel }}," +
                              "{{ val.date_of_refund }}," +
                              "{{val.mode_of_refund}}," +
                              "{{val.type_of_refund}}" +
                              "{{ val.refund_cheque_no }}," +
                              "{{val.refund_amount}}," +
                              "{{val.issued_by}}," +
                              "{{ val.sitevist.executive.first_name }}," +
                              "{{val.sitevist.executive.executive_set.last.teamlead.sr_team.project_head.first_name}}," +
                              "{{ val.land_details.plotsize.plotsize }}\n";
            {% endif %}                  
            {% endfor %}

            // Create a data URI and trigger the download
            var encodedUri = encodeURI(csvContent);
            var link = document.createElement("a");
            link.setAttribute("href", encodedUri);
            link.setAttribute("download", "Cancel Report.csv");
            document.body.appendChild(link); // Required for Firefox
            link.click();
        });
    });
</script>
{% endblock %}